include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = CocoaOpenGL
APP_NAME = CocoaOpenGL
CoreBreach_APPLICATION_ICON = Cocoa_GL.icns

ADDITIONAL_OBJC_LIBS = -lGL -lGLU

CocoaOpenGL_HEADERS = AppDelegate.h BasicOpenGLView.h GLString.h trackball.h
CocoaOpenGL_OBJC_FILES = AppDelegate.m BasicOpenGLView.m GLString.m main.m
CocoaOpenGL_C_FILES = trackball.c
CocoaOpenGL_RESOURCE_FILES = English.lproj/MainMenu.nib
CocoaOpenGL_MAIN_MODEL_FILE = MainMenu.nib


include $(GNUSTEP_MAKEFILES)/application.make



